### ISSUE TITLE
shelf_router_generator: does not handle `$` in the URL

### ISSUE THREAD

**Issue by kevmoo** [google/dart-neats#10]
See https://github.com/dart-lang/json_serializable/blob/master/json_serializable/lib/src/utils.dart#L168 for help!

**Comment by jonasfj** [comment]
I assume this is a problem with code generation when the URL-patterns contain `$`, and not to do with the actual URLs for requests coming in.

We are using `code.literal` from `package:code_builder`, so this might be something that needs fixing there.

https://github.com/google/dart-neats/blob/1cbc6bb0e93e7df630d0582da51abc663adf206f/shelf_router_generator/lib/src/shelf_router_generator.dart#L98-L102

**Comment by kevmoo** [comment]
Correct. Code generation.

**Comment by jonasfj** [comment]
Fixed in #16.
