### ISSUE TITLE
Error in README example

### ISSUE THREAD

**Issue by erf** [google/dart-neats#108]
README says:

```
var app = Router();
var server = await io.serve(app.handler, 'localhost', 8080);
```

but  Router does not have a `handler`, and i believe it should say:

```
var app = Router();
var server = await io.serve(app, 'localhost', 8080);
```

This works, but `Router` is not a `Handler`, so not sure why it works??

**Comment by rlatjdyd7942** [comment]
In the Router class, call method is defined so that it can be work like a handler
https://github.com/google/dart-neats/blob/640b2d35751f8024a2d941808f38b2c62d1fd35e/shelf_router/lib/src/router.dart#L135-L151

**Comment by jonasfj** [comment]
Closed with https://github.com/google/dart-neats/pull/129
