### ISSUE TITLE
Move ChunkStreamIterator to package:async

### ISSUE THREAD

**Issue by jonasfj** [google/dart-neats#117]
Let's propose `ChunkStreamIterator` for `package:async`.

TODOs:
 *  [x] Document what happens when calling `read` before previous call is done (pretty sure it's a `StateError`, let's also test this).
 *  [ ] Consider adding an optional `makeList` function or `listBuilder` abstraction in place of the extension for `ChunkedStreamIteratorByteStreamExt`

**Comment by jonasfj** [comment]
Filed -> https://github.com/dart-lang/async/pull/161

**Comment by simolus3** [comment]
You might want to also mark the package as discontinued on pub.dev if it's not supposed to be used anymore?
