### ISSUE TITLE
Update source_gen and publish on pub

### ISSUE THREAD

**Issue by CodeDoctorDE** [google/dart-neats#119]
There is no new version on pub: https://pub.dev/packages/shelf_router_generator
And please update source_gen to 1.0.0 (https://pub.dev/packages/source_gen) because I use another package which depend on this.

**Comment by CodeDoctorDE** [comment]
@kevmoo any updates?

**Comment by kevmoo** [comment]
This is mostly @jonasfj package. I was waiting for code_builder to get migrated so we can do one big push that makes things null safe.

**Comment by CodeDoctorDE** [comment]
It's very important for me. My database dependencies uses a newer source gen and I want to use it for my rest api.
If there is anything I can help, feel free to contact me :)

**Comment by kevmoo** [comment]
It looks like code_builder should be out soon as null safe. Then we can
jump on this!

**Comment by CodeDoctorDE** [comment]
code_builder 4.0 was released: https://pub.dev/packages/code_builder/changelog

**Comment by kevmoo** [comment]
We also have to wait for the build infrastructure (pkg:build_runner, etc) to get migrated.

Thanks for your patience!

**Comment by CodeDoctorDE** [comment]
> We also have to wait for the build infrastructure (pkg:build_runner, etc) to get migrated.
> 
> Thanks for your patience!

oh, i saw it was migrated: https://pub.dev/packages/build_runner
