### ISSUE TITLE
[Question] Can this be used for scheduling background tasks for Android/iOS like Workmanager ?

### ISSUE THREAD

**Issue by luvishq** [google/dart-neats#121]
Can this be used for scheduling background tasks for Android/iOS like how workmanager does ?

Also , if this is not meant for it, which flutter package do you suggest for that? 

Any help would be really appreciated

**Comment by jonasfj** [comment]
Not sure what package you're talking about, this is a mono-repo with multiple packages.

If it's neat_periodic_task I would think not, it's not a package targeting Flutter. It's mainly aimed at running periodic tasks on a server or in a background process like a cron job..
