### ISSUE TITLE
can't access boundary or do not know where it is

### ISSUE THREAD

**Issue by trailerzone** [google/dart-neats#134]
I am trying to get a file from the client server side, I have been piecing together code but cannot  request.headers.contentType.paramers['boundary]; I know it is found in the core which shelf_router is built upon, is there any way I can access this information going about it a different way? I am able to get the data using this code below

      var dataBytes = <int>[];

      await for (var data in req.read()) {
        dataBytes.addAll(data);
      }

but unsure how to use mime to convert this to it correct type, i would use another package but I already built a ton upon shelf_router so I would like to stick with it, thanks

**Comment by jonasfj** [comment]
How is this related to `shelf_router`?

Using `mime` with `shelf` is not trivial.. but it can be done, we did it here:
https://github.com/dart-lang/pub-dev/blob/04727e95ce9c4c048a29f1ff5180568e3d24ed97/app/lib/fake/server/fake_storage_server.dart#L63-L89
