### ISSUE TITLE
Error with route that is not found - read method can only be called once on a shelf.Request/shelf.Response Object

### ISSUE THREAD

**Issue by rmtmckenzie** [google/dart-neats#149]
When using the router, for items which cannot be found an error is being produced by default.

The default handler simply returns the _same_ response every time it is called, meaning that the second time it is returned, it throws an error.

This is the line in question: 

```dart
static Response _defaultNotFound(Request request) => routeNotFound;
```

and

```dart
Router({Handler notFoundHandler = _defaultNotFound})
    : _notFoundHandler = notFoundHandler;
```

I'll submit a PR to fix this shortly.

**Comment by isoos** [comment]
@rmtmckenzie are you using 1.1.1? I think the issue was fixed in that.

**Comment by rmtmckenzie** [comment]
hmmm. I thought I was but my pubspec.lock says otherwise. I'll give it a test.

**Comment by rmtmckenzie** [comment]
Yeah that seems to have fixed it. Thanks for the super quick response!
