### ISSUE TITLE
router.get method should be able to pass context

### ISSUE THREAD

**Issue by erayerdin** [google/dart-neats#157]
Current signature of `router.get` function is `router.get(String path, FutureOr<Response> Function(Request) func)`.

I'm in favor of using *class-based* and *controller-like* classes. Currently, below is what I do:

```dart
class BooksController {
  Future<Response> call(Request request) async {
    // returns a list of books as json
  }
}
```

...and I pass this thing to `router` instance doing...

```dart
router.get('/books', BooksController());
```

However, I'd like to extend this. I'd like to also have `/books/123`, `/books/create` etc. and I'd like to do this in one controller.

The thing is, there is `request.context` property of type `Map<String, dynamic>`, which would be an excellent candidate to implement this behavior. However, there's currently no way to pass additional context to `request.context` with `router.get`. If I was able to do, the code would be much cleaner. See the example:

```dart
// route definitions
router.get('/books', BooksController());
router.get('/books/<id>', BooksController(), context: {'reqtype': 'readOne'});
router.put('/books', BooksController(), context: {'reqtype': 'create'});
router.delete('/books/<id>', BooksController(), context: {'reqtype': 'delete'});

// controller
class BooksController {
  Future<Response> call(Request request) async {
    String reqtype = request.context['reqtype'];
    switch (reqtype) {
      case 'readOne':
        readOne(request);
      case 'create':
        create(request);
      case 'delete':
        delete(request);
      // default is whatever, you get the point
    }
  }

  Future<Response> readOne(Request request) async {}
  Future<Response> create(Request request) async {}
  Future<Response> delete(Request request) async {}
}
```

**Comment by EmreSURK** [comment]
hi @jonasfj 
The context object of the router is immutable while using like router.get, it is mutable while using annotations?

**Comment by erayerdin** [comment]
@EmreSURK 
I'm not dealing with shelf right now but you can shallow copy it if the context is a subtype of `Map` I believe. Assuming you have an immutable `Map` named `context`:

```
Map mutableContext = Map.from(context);
```

...should do the deal I guess.

**Comment by jonasfj** [comment]
You could also do:
`router.put('/books', BooksController(context: {'reqtype': 'create'}));`

Not sure why an untyped context is desirable.

Closing this as shelf_router has moved, and I'm not sure this was necessary.
