### ISSUE TITLE
add support to execute task in isolated (in background outside the main thread)

### ISSUE THREAD

**Issue by insinfo** [google/dart-neats#160]
add support to execute task in isolated (in background outside the main thread)

**Comment by paurakhsharma** [comment]
This would be awesome to have. 
Maybe when running on the web use something like `web workers`

**Comment by alg520** [comment]
Any change of plans?

**Comment by jonasfj** [comment]
No, plans this is not the purpose of this package.

The package is for ensuring that some tasks runs periodically in a cloud environment. Where and how that task runs is not something this package cares about. There is absolutely no reason you can't trigger the task to run in a background isolate, and no reason you couldn't write a package that runs a function in a background isolate when called. Then you could trigger this using this package.

This package is about scheduling reliably.
