### ISSUE TITLE
get current attempt times

### ISSUE THREAD

**Issue by zysc8313** [google/dart-neats#163]
Would that be possible that I can get current attempt times in the onRetry callback function?

**Comment by ibhanu** [comment]
@zysc8313 you can checkout this: [https://github.com/ibhanu/dart-neats/tree/master/retry](https://github.com/ibhanu/dart-neats/tree/master/retry)

I don't know is it PR worthy.

**Comment by zysc8313** [comment]
@ibhanu Thank you! that's definitely a good PR

**Comment by ibhanu** [comment]
@zysc8313 done [https://github.com/google/dart-neats/pull/164](https://github.com/google/dart-neats/pull/164)

**Comment by jonasfj** [comment]
This is breaking, I'd suggest making a different better retry package :)
