### ISSUE TITLE
[sanitize_html] Why section tag not allowed?

### ISSUE THREAD

**Issue by x-yurii-uvarov** [google/dart-neats#166]
The `<section>` tag is allowed in the [dompurify package](https://www.npmjs.com/package/dompurify), and I'm surprised it's not allowed in this package. 
Is there any reason why this tag is not included in the list of allowed tags?

**Comment by jonasfj** [comment]
The definition of what is sane to allow is subjective. This package aims to make injection of rendered markdown safe.
Hence, why the README says:
> This package uses an HTML5 parser to build-up an in-memory DOM tree and filter elements and attributes, in-line with [rules employed by GitHub](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/sanitization_filter.rb) when sanitizing GFM (GitHub Flavored Markdown).

It's also useful for other things. But it doesn't aim to be anything that can possibly be considered safe by some definition.

I just sort of decided to use the same subset as github, it's a reasonably sane subset, as in it's hard to accidentally completely mess up the layout of the page the HTML is injected into.
(I'm not confident that it's impossible to mess up the layout of the embedding page).
