### ISSUE TITLE
Enabling retry on any type of thrown errors

### ISSUE THREAD

**Issue by bgenidy** [google/dart-neats#191]
Can we consider updating this line https://github.com/google/dart-neats/blob/master/retry/lib/retry.dart#L132 to catch any error thrown instead of type Exception and pass it to the `retryIf` operator.

Also if library doesn't want to introduce breaking changes maybe introducing a more generic retry attribute to support this functionality.

```dart
try {
  await fun();
} catch (e) {
  if (e is Exception) {
    await retryIf(e);
  }
  else {
    await retryGenericIf(e);
  }
}
```

**Comment by isoos** [comment]
`retry` in this case is very opinionated, with the idea that we won't retry `Error`s by default. Most `Error` thrown in the SDK indicates a state or input that is unlikely to change with a second attempt. If it is part of a larger process that you want to retry on errors, I'd suggest to wrap them in try-catch and throw a wrapper Exception.

**Comment by bgenidy** [comment]
thanks makes sense I can continue wrapping the execution logic
