### ISSUE TITLE
Callback for time left until next task.

### ISSUE THREAD

**Issue by Prn-Ice** [google/dart-neats#196]
I'd like to know how much time until the next execution of the task.
 * Looking through the code, I believe this is the `_interval` variable.
 * Is there some way that this can be exposed via a callback?
 * I would be open to fixing this in a pull request if you give me some pointers.

```dart
// I think this would look like
_scheduler = NeatPeriodicTaskScheduler(
      interval: const Duration(seconds: 30),
      name: 'periodic-results-calculation',
      timeout: const Duration(seconds: 5),
      task: _calculateResult,
      onIntervalChanged: (val){
        print(val);
      },
      minCycle: const Duration(seconds: 5),
    );
```

**Comment by jonasfj** [comment]
I believe `delay - elapsed` in:
https://github.com/google/dart-neats/blob/5119eba0db931caa37c207634f52f12d5ae4f4da/neat_periodic_task/lib/neat_periodic_task.dart#L243-L250

Is time until next time it's supposed to run.

side note: It's possible that `var d = delay - elapsed;` would actually be better logic. Maybe, + some randomness to reduce racing.

We could expose this as a property on `NeatPeriodicTaskScheduler`, like `_scheduler.nextRun` that returns a `DateTime`.

But until `start()` have been called, and we've reached the lines above in the loop we don't really have anything to return. We could return `DateTime(0)` as a dummy value.

It's also not accurate, this is an estimate at best.

----------

`NeatPeriodicTaskScheduler` isn't aimed at precision scheduling of tasks. It's aimed at scheduling tasks where the state of the task is persisted in GCS, S3, Cloud Datastore, Firestore or a database of sorts. It only requires optimistic concurrency from the state storage.

Indeed the goal, is to reliably scheduled a periodic task that is supposed to run on a daily or weekly basis. And ensuring that the task is retried if it fails, etc.

**Comment by jonasfj** [comment]
If you can define good semantics for what this property should return, and write up good documentation for it, I'm open to taking a PR.

Please make an outline of what it could look like here, and then ping me with `@jonasfj`.

**Comment by Prn-Ice** [comment]
Thanks for taking the time to look at this jonas. I wound up using the default flutter timer and forgot to update the issue.
