### ISSUE TITLE
Update to make RetryOptions final is breaking mocks

### ISSUE THREAD

**Issue by ricardoamador** [google/dart-neats#208]
* The change to make RetryOptions final is breaking Mocks.
 * https://github.com/google/dart-neats/pull/207 <- causes breakages in test with update to 3.1.2.

```
test/src/utilities/mocks.mocks.dart:127:60: Error: The class 'RetryOptions' can't be implemented outside of its library because it's a final class.
  class _FakeRetryOptions_7 extends _i1.SmartFake implements _i8.RetryOptions {
```

**Comment by jonasfj** [comment]
I'm not sure I want to allow mocking here. Why is that necessary?

Making it a `final class` means that we are free to add new properties in the future.

In general I was really happy to see `final class` so I can stop people from doing things I didn't imagine, hehehe
No, it's mostly that is so sad if we have bump major versions for trivial changes like adding new properties. So unless I see a good reason for something to not be `final` then it should be a `final class`.

-------------


If there is a useful pattern here that I'm missing I'm all ears. I wouldn't necessarily mind adding a `RetryOptions.mock` constructor or something like that.

**Comment by ricardoamador** [comment]
I am not sure that making it final would prevent you from needing to release a new package if a property is added but this is fine. While a mock would be nice it just meant we needed to refactor code. No problem here.
