### ISSUE TITLE
Default behavior of (no) retryIf

### ISSUE THREAD

**Issue by karl3i** [google/dart-neats#22]
Hello,

according to the _v3.0.0_ changelog, the behavior if we don't input any _retryIf_ is to have any exception being considered for the retry.

Does this means that this code snippet:

```
final response = await retry(
  // Make a GET request
  () => http.get('https://google.com').timeout(Duration(seconds: 5)),
  // No explicit retry 
);
```
is the same as:

```
final response = await retry(
  // Make a GET request
  () => http.get('https://google.com').timeout(Duration(seconds: 5)),
  // Retry on Exception
  retryIf: (e) => e is Exception,
);
```
And also meaning that the call will be retried if:

- it didn't answer within 5 seconds
- it threw an(y) exception 

thanks.

**Comment by jonasfj** [comment]
Yes, the two snippets are equivalent.

In fact, this is also equivalent to:
```
final response = await retry(
  // Make a GET request
  () => http.get('https://google.com').timeout(Duration(seconds: 5)),
  // Retry on Exception
  retryIf: (e) => true,
);
```

Retries will not be consider if no exception is thrown.

------
Prior to version `3.0.0` the `retry()` function would never retry anything, unless a `retryIf` function was given...
The thinking was that one should never blindly retry on any exception. But in practice, you're often writing up something quick and dirty, and retrying on any `Exception` (not `Error`) should be safe.

------
I hope that answers you're question. If not please reopen.. Also feel free to file PRs for additional documentation comments / examples that you think might help others.
