### ISSUE TITLE
How to catch the last exception at maxAttempts?

### ISSUE THREAD

**Issue by karl3i** [google/dart-neats#25]
Hello,

I'd like to know how to handle the case when an exception is thrown for the last attempt.

With maxAttempts set to, say, 3, let's consider the following responses: 

1. Exception -> retry
2. Exception -> retry
3. Exception -> give up

Do I have a way to catch the exception only if this is the last attempt? Should I surround the whole retry part with a try/catch?

>try {
>final response = await retry(
  // Make a GET request
  () => http.get('https://google.com').timeout(Duration(seconds: 5)),
  // Retry on Exception
  retryIf: (e) => true,
);
}
catch(e) {
  // do something with $s
}

Thanks.

**Comment by jonasfj** [comment]
```
try {
  final response = await retry(
    () => http.get('https://....').timeout(Duration(seconds: 15)),
  );
} on TimeoutException {
  // Handle timepout
} catch (e, st) {
  // Handle any error/exception e, with stacktrace st
}
```

See more about exception handling here:
https://dart.dev/guides/language/language-tour#catch

Notice, that this will only catch the last exception after `maxAttempts` have been exhausted.

-----

For how to write code snippets in github comment see:
https://help.github.com/en/articles/creating-and-highlighting-code-blocks
