### ISSUE TITLE
Reponse class in route handler

### ISSUE THREAD

**Issue by ansarizafar** [google/dart-neats#30]
Currently router handlers only receive Request class as argument and we have to import shelf package everywhere to send a response. It would be great If route handlers are also provided with Response class as argument

```
//Current 
router = Router();
router.get('/', (Request request) {
    return Response.ok('Home Page');
  });

// Proposed
router.get('/', (Request request, Response response) {
    return response.ok('Home Page');
  });
```

**Comment by jonasfj** [comment]
`Reponse.ok` is a static method, not an instance method..

Maybe a trick would be to export `Response` from this package.

**Comment by ansarizafar** [comment]
Why not just pass Response class to route handler as argument with request class?

**Comment by jonasfj** [comment]
I don't think that's will work / is possible, without modifying `package:shelf`.

But exporting `Request` and `Response` from the `shelf_router.dart` library doesn't seem controversial.

**Comment by jonasfj** [comment]
That would remove the need for:
```dart
import 'package:shelf/shelf.dart';
```

**Comment by jonasfj** [comment]
What is the concern? Request is less discoverable because you can't find it from auto-complete?

**Comment by jonasfj** [comment]
I'm going to close this as I have no resolution. We could possibly export the `Request` and `Response` objects. But adding in the handler signature seems wrong.
