### ISSUE TITLE
Using `router.get` should add a default handler for `router.head`

### ISSUE THREAD

**Issue by jonasfj** [google/dart-neats#34]
We should add default handlers for `HEAD` when we have handlers for `GET`.
Probably we can just serve the response from the `GET` handler if there is no other handler registered that handles the `HEAD` request.

```dart
// when writing
router.get('/', myHandler);
// we should implicitly add:
router.head('/', myHandler); // if and only if, no other registered handler matches the HEAD request.
```

@isoos, does this sound like a reasonable solution to you? I think this might solve some problems for us in `pub.dev`.

**Comment by isoos** [comment]
I think this could work just fine, but I'd probably make this explicit, e.g. `router.get('/', myHandler, acceptHead: true)`.

**Comment by jonasfj** [comment]
Hmm, I sort of oppose making it explicit, because we need to write this everywhere.

Handling `get` but not `head` is always a mistake.

**Comment by Ehesp** [comment]
@jonasfj I've just been looking into this one and stumbled across the source code of this PR - I'm a bit confused as to why a HEAD request is always added if a GET handler is?

I understand the purpose of a HEAD request (I think) however shouldn't this be something an application developer should be left to handle? 

> Handling get but not head is always a mistake.

Not arguing this, just more curious as to why it is always a mistake?

**Comment by jonasfj** [comment]
> Ok just done some more reading, this makes sense now! :D

Thanks, yes. IMO, implementing `GET` but not `HEAD` is always wrong :)
