### ISSUE TITLE
shelf_router_generator fails to generate route when project has extension on String

### ISSUE THREAD

**Issue by radzish** [google/dart-neats#35]
If I define extension on String then route is failed to be generated with message "The shelf_router.Route annotation can only be used on shelf request handlers accept a shelf.Request parameter and/or a shelf.Request parameter and all string parameters in the route, the "<param_name>" parameter is not of type string"
 
shelf_router_generator: 0.7.2+2

**Comment by jonasfj** [comment]
Code snippet? I can't confirm... Presumably you have a different bug.

**Comment by jonasfj** [comment]
Please reopen if you have a gist or code snippet that can reproduce.

**Comment by radzish** [comment]
Route method looks like:

```
  @Route.get("/my-api/<kind>")
  Future<Response> myApi(Request request, String kind) async {
   ...
```

Extension looks like:
```
extension Blank on String {
  bool get isBlank => this == null || trim().isEmpty;

  bool get isNotBlank => !isBlank;
}
```

I get error:
```
The shelf_router.Route annotation can only be used on shelf request handlers accept a shelf.Request parameter and/or a shelf.Request parameter and all string parameters in the route, the "kind" parameter is not of type string
package:my_resource.dart:19:64
   ╷
19 │   Future<Response> myApi(Request request, String kind) async {
   │                                                                ^^^^
```

If I delete extension, everything works fine. 

I did debugging and noticed that shelf_router_generator.dart
```
      if (!_stringType.isExactlyType(p.type)) {
```
returns false if extension is in place, because p.type is "dynamic", not "String" for parameter "kind", not sure why. Maybe bug in analyzer package.

So this is a bug. Currently I commented out that check as a workaround.

**Comment by radzish** [comment]
Please re-open, as I can not do it myself

**Comment by radzish** [comment]
Finally I found cause: I used another generator (kiwi_generator) that has dependency on analyzer < 0.37. Looks like that old analyzer does not handle extensions at all, that was causing a bug.

**Comment by jonasfj** [comment]
hmm, that's sounds plausible.
