### ISSUE TITLE
Split stream using a delimiter?

### ISSUE THREAD

**Issue by Mirageofmage** [google/dart-neats#42]
Is it possible to split an incoming stream by using a delimiter?

I have a stream of bytes I want to read that are exactly 154 bytes long, but due to BLE limitations are transmitted in 7 chunks of 20 and 1 chunk of 14. 

Sometimes when I connect to the data stream, the buffered information doesn't start reading the information from the start of the packet, and will instead split the packet and overflow.

Eg. (Instead of 7 * 20 + 1 * 14, I'll get 3 * 20 + 1 * 14 + 4 * 20)

Example code:
```dart
StreamSubscription<List<int>> data;
ChunkedStreamIterator<int> dataChunked;
 ...
if (c.uuid == new Guid("0000ffe1-0000-1000-8000-00805f9b34fb")) {
          await c.setNotifyValue(true);
          dataChunked = ChunkedStreamIterator(c.value);
          //Also works, dataChunked = ChunkedStreamIterator(bufferChunkedStream(c.value, bufferSize: 154));
      while (true) {
            var data = await dataChunked.read(154); // read whole packet
            if (data.length < 0) {
              print('End of file reached');
              break;
            }
            parseData(data); //Splits data into sublists
            setState(() {
              buffer = data;
              count++;
            });
      }
} else {print("Nope"); }

```

**Comment by isoos** [comment]
@Mirageofmage: If you want to slice the stream into chunks with pre-determined sizes, you could also use `package:buffer`'s sliceStream: https://pub.dev/documentation/buffer/latest/buffer/sliceStream.html

**Comment by Mirageofmage** [comment]
I was able to solve my issue by doing array rotations after the the stream was chunked together.
