### ISSUE TITLE
flutter_test is no longer compatible with pem

### ISSUE THREAD

**Issue by sebastiancadena** [google/dart-neats#48]
* `flutter_test` is no longer compatible with `pem`, since `flutter_test` requires `petitparser ^3.0.0`, and `pem` depends on `petitparser ^2.1.1`.
 * I'm currently using the latest stable version of the Flutter SDK: **Flutter 1.17.5**

**Comment by jonasfj** [comment]
Filed https://github.com/google/dart-neats/pull/49 to fix this.

**Comment by jonasfj** [comment]
Fixed in version 1.0.1
