### ISSUE TITLE
Nested `ChunkedStreamIterator` propagates pausing

### ISSUE THREAD

**Issue by walnutdust** [google/dart-neats#66]
If we were to call `ChunkedStreamIterator` on a `ChunkedStreamIterator.substream`, the pausing propagates, leading to more pauses than expected on the parent `ChunkStreamIterator`.

```dart
  test('pause propagation', () async {
    final s = ChunkedStreamIterator(_chunkedStream([
      ['a', 'b', 'c'],
      ['1'],
      ['2'],
    ]));
    expect(await s.read(1), equals(['a']));
    final sub = s.substream(3);
    final c = ChunkedStreamIterator(sub);
    expect(await c.read(3), ['b', 'c', '1']);  /// Line (a)
    expect(await c.read(1), []); /// This line makes no difference to the result.
    expect(await s.read(1), equals(['2']));
  });
```

I think the following program flow is what causes the error:

1. In Line (a), the parent `ChunkedStreamIterator`, `s`, pauses after delivering the `['1']` block. 
1. At the same time, since `c` has delivered its full length, `c` will be `reset`. 
1. `reset` calls `_subscription.pause`, which calls `pause` in the substream controller for `sub`.
1. The controller for `sub` pauses the original stream subscription in `s`. 

The end result of this is that `s`'s stream subscription is paused multiple times, which causes future `read`s on `s` to fail because the subscription still remains paused.

**Comment by jonasfj** [comment]
hmm, an ideas how we fix this?
 
Is it reasonable that when a substream has been consumed then it should not pause the original stream?

**Comment by walnutdust** [comment]
I'm not very sure what a good fix for this is D:

I think pausing the original stream makes sense because if it were a broadcast stream, simply pausing on the substream might cause us to miss elements?

This is also kind of a weird issue which only happens when the end of the nested `ChunkedStreamIterator` coincides with the end of a block in the parent stream, and the pause behavior seems to work just fine?

If we didn't pause the original stream, would the original stream not still send elements, causing the nested `ChunkedStreamIterator` to continue receiving elements, which might cause an overriding of the `lastChunk` and lead to incorrect results?

Please let me know if I'm thinking through this wrong! Still not very confident with streams (especially in this case nested `ChunkedStreamIterator`s aha)
