### ISSUE TITLE
Mounts should not require trailing slashes

### ISSUE THREAD

**Issue by joshpennington** [google/dart-neats#67]
* When using the mount function a trailing slash is required.
* This makes it impossible to have a mounted route that does not require that a tailing slash be required
* In example below the URL "/product" would result in a 404
* "/product/" would return the expected result

```dart
void main(List<String> args) async {
  load();

  var router = Router();

  router.mount('/auth/', AuthRoutes().router);
  router.mount('/product/', ProductRoutes().router);

  // Final route to return a not found
  router.all('/<.*>', (request) => shelf.Response.notFound(''));

  var handler = const shelf.Pipeline()
    .addMiddleware(shelf.logRequests())
    .addMiddleware(shelf.createMiddleware(requestHandler: AuthManager.handle))
    .addMiddleware(shelf.createMiddleware(requestHandler: ProductController.SecureMiddleware))
    .addHandler(router.handler);

  await io.serve(handler, 'localhost', int.parse(env['PORT'])).then((server) {
    print('Server running on port ${server.port}');
  });

}

class ProductRoutes {

  static FutureOr<Response> middleware(Request request) async {
    print("ProductRoutes Middleware");
    return null;
  }

  Router get router {
    final router = Router();

    var c = ProductController();

    router.get('/', c.GetList);
    router.get('/<product_id>', c.GetById);

    return router;
  }

}
```

**Comment by ab36245** [comment]
I agree. This is tripping me up at the moment as well.

**Comment by jonasfj** [comment]
I can see how this makes sense...

https://github.com/google/dart-neats/blob/783d6bac4d07b7ac55fe9d4a2f4d194bc90cf55c/shelf_router/lib/src/router.dart#L122-L133

I wonder what the implications are if we just remove `|| !prefix.endsWith('/')`, and allow `prefix` without trailing slash?

Will [`Request.change`](https://pub.dev/documentation/shelf/latest/shelf/Request/change.html) work as expected?

And how will it work if there is multiple slashes in the request, will then start to match it incorrectly?

**Comment by iampopal** [comment]
Mount should not require trailing slashes, waiting for a fix.

**Comment by matsp** [comment]
@jonasfj I successfully tested the removal of `|| !prefix.endsWith('/')`. Can you give me hints which test cases I should include in a potential MR?

This issue is almost one year old - let's fix it 👍

**Comment by matsp** [comment]
I started the PR #140. Maybe someone else can help out to find an occuring issue.
