### ISSUE TITLE
addLinkRel not really optional when used from sanitizeHtml

### ISSUE THREAD

**Issue by ditman** [google/dart-neats#71]
The new `addLinkRel` method is called [unconditionally](https://github.com/google/dart-neats/blob/master/sanitize_html/lib/src/sane_html_validator.dart#L253) but it might be null when calling the `sanitizeHtml` function directly, since it's optional according to [its interface](https://github.com/google/dart-neats/blob/master/sanitize_html/lib/sanitize_html.dart#L78).

This is [breaking things](https://github.com/flutter/flutter/issues/67854#issuecomment-707781063).

Both `allowElementId` and `allowClassName` do [null](https://github.com/google/dart-neats/blob/master/sanitize_html/lib/src/sane_html_validator.dart#L241) [checks](https://github.com/google/dart-neats/blob/master/sanitize_html/lib/src/sane_html_validator.dart#L244) before being used.

Example code:

```dart
sanitizeHtml('<a href="good-link">hello'); // boom
```

**Comment by jonasfj** [comment]
Wow, obvious bug... Thanks for the PR.

**Comment by ditman** [comment]
No problem, thanks for the package! :P
